-- USUÁRIO TESTE
insert into usuario (login_usuario, nome_usuario, senha_usuario, email_usuario, cargo_usuario, tipo_usuario)
values ('teste', 'teste', 'teste', 'jj@ifsul.edu.br', 'Secretário', 1);

INSERT INTO preferencia (nome_preferencia, escolha_preferencia) VALUES
(1, 1),    -- 1 [1,2] - Modo de uso [clinica, instituicao]
(2, 1);    -- 2 [1,2] - Logotipo do software [Logo VetSof, Logo personalizado]

INSERT INTO estilo (nome_estilo, ativo_estilo) VALUES 
('estiloPadrao.css', 1),
('blueSky.css', 0);

INSERT INTO valores_padrao (codigo_valores_padrao, valor_valores_padrao, string_valores_padrao) VALUES
(1, null, null),
(2, null, null);

-- MUNICÍPIOS
INSERT INTO municipio (nome_municipio, estado_municipio) VALUES
-- Municípios do Vale do Taquari
('Anta Gorda', 'RS'),            -- 1
('Arroio do Meio', 'RS'),
('Arvorezinha', 'RS'),
('Bom Retiro do Sul', 'RS'),
('Canudos do Vale', 'RS'),
('Capitão', 'RS'),
('Colinas', 'RS'),
('Coqueiro Baixo', 'RS'),
('Cruzeiro do Sul', 'RS'),
('Dois Lajeados', 'RS'),       -- 10
('Doutor Ricardo', 'RS'),
('Encantado', 'RS'),
('Estrela', 'RS'),
('Fazenda Vilanova', 'RS'),
('Forquetinha', 'RS'),
('Ilópolis', 'RS'),
('Imigrante', 'RS'),
('Lajeado', 'RS'),
('Marques de Souza', 'RS'),
('Muçum', 'RS'),             -- 20
('Nova Bréscia', 'RS'),
('Paverama', 'RS'),
('Poço das Antas', 'RS'),
('Pouso Novo', 'RS'),
('Progresso', 'RS'),
('Putinga', 'RS'),
('Relvado', 'RS'),
('Roca Sales', 'RS'),
('Santa Clara do Sul', 'RS'),
('Sério', 'RS'),            -- 30
('Tabaí', 'RS'),
('Taquari', 'RS'),
('Teutônia', 'RS'),
('Travesseiro', 'RS'),
('Vespasiano Correa', 'RS'),
('Westfália', 'RS'),
-- Municípios do Vale do Rio Pardo
('Arroio do Tigre', 'RS'),
('Boqueirão do Leão', 'RS'),
('Candelária', 'RS'),
('Encruzilhada do Sul', 'RS'),    -- 40
('Estrela Velha', 'RS'),
('General Câmara', 'RS'),
('Herveiras', 'RS'),
('Ibarama', 'RS'),
('Lagoa Bonita do Sul', 'RS'),
('Mato Leitão', 'RS'),
('Pantano Grande', 'RS'),
('Passa Sete', 'RS'),
('Passo do Sobrado', 'RS'),
('Rio Pardo', 'RS'),              -- 50
('Santa Cruz do Sul', 'RS'),
('Segredo', 'RS'),
('Sinimbu', 'RS'),
('Sobradinho', 'RS'),
('Tunas', 'RS'),
('Vale do Sol', 'RS'),
('Vale Verde', 'RS'),
('Venâncio Aires', 'RS'),         -- 58
('Vera Cruz', 'RS');

-- BAIRROS
INSERT INTO bairro (fk_idmunicipio_bairro, nome_bairro) VALUES
-- Bairros de Venâncio Aires (ID 58)
(58, 'Centro'),
(58, 'Brígida'),
(58, 'Cruzeiro'),
(58, 'Gressler'),
(58, 'Aviação'),
(58, 'Morsch'),
(58, 'Coronel Brito'),
(58, 'Santa Tecla'),
(58, 'Macedo'),
(58, 'Batista'),
(58, 'Cidade Alta'),
(58, 'União'),
(58, 'Mariante'),
(58, 'Vila Freese'),
(58, 'Linha Travessa'),
(58, 'Estância Nova'),
(58, 'Vila Táta'),
-- Bairros de Santa Cruz do Sul (ID 51)
(51, 'Centro'),
(51, 'Arroio Grande'),
(51, 'Ana Nery'),
(51, 'Bom Jesus'),
(51, 'Goethe'),
(51, 'Higienópolis'),
(51, 'Linha João Alves'),
(51, 'Santo Inácio'),
(51, 'Santo Antônio'),
(51, 'Universitário'),
(51, 'Senai'),
(51, 'Belvedere'),
(51, 'Esmeralda'),
(51, 'Rauber'),
(51, 'Progresso'),
(51, 'Aliança'),
(51, 'Renascença'),
(51, 'Verena'),
(51, 'Linha Santa Cruz'),
(51, 'Linha Pinheiral'),
(51, 'Pedreira'),
(51, 'Linha São José'),
(51, 'Linha Marechal'),
(51, 'Monte Verde'),
-- Bairros de Lajeado (ID 18)
(18, 'Centro'),
(18, 'Americano'),
(18, 'São Cristóvão'),
(18, 'Florestal'),
(18, 'Moinhos'),
(18, 'Campestre'),
(18, 'Conventos'),
(18, 'Montanha'),
(18, 'Carneiros'),
(18, 'Universitário'),
(18, 'Jardim do Cedro'),
(18, 'Hidráulica'),
(18, 'Santo André'),
(18, 'Bom Pastor'),
(18, 'Olarias'),
(18, 'Planalto'),
(18, 'Irmãos Maristas'),
(18, 'São Bento'),
(18, 'Moinhos D’Água'),
(18, 'Santo Antônio'),
(18, 'Nações'),
(18, 'Morro 25'),
(18, 'Imigrante'),
(18, 'Alto do Parque'),
(18, 'Morro do Espelho'),
(18, 'São José'),
(18, 'Floresta'),
(18, 'Santa Clara'),
(18, 'Novo Tempo'),
(18, 'Vila Zwirtes'),
(18, 'Vila dos Portões');

-- ESPÉCIES
INSERT INTO especie (nome_especie) VALUES
('Canino'),
('Felino'),
('Coelho'),
('Equino'),
('Suíno'),
('Bovino'),
('Ave');

-- RAÇAS
INSERT INTO raca (nome_raca, fk_idespecie) VALUES
-- Raças de Caninos (fk_idespecie = 1)
('Labrador Retriever', 1),
('Bulldog Francês', 1),
('Pastor Alemão', 1),
('Golden Retriever', 1),
('Beagle', 1),
('Poodle', 1),
('Shih Tzu', 1),
('Chihuahua', 1),
('Rottweiler', 1),
('Dachshund', 1),
('Border Collie', 1),
('Boxer', 1),
('Schnauzer', 1),
('Basset Hound', 1),
('Cocker Spaniel', 1),
('Doberman', 1),
('Yorkshire Terrier', 1),
('Pitbull', 1),
('Maltês', 1),
('Bulldog Inglês', 1),
('Jack Russell Terrier', 1),
('Pug', 1),
('Saint Bernard', 1),
('Shiba Inu', 1),
('Cavalier King Charles Spaniel', 1),
('Newfoundland', 1),
('Akita', 1),
('Husky Siberiano', 1),
('Chow Chow', 1),
('Mastim Napolitano', 1),
('Weimaraner', 1),
('Cocker Spaniel Inglês', 1),
('Collie', 1),
('Malamute do Alasca', 1),
('Samoyed', 1),
('Australian Shepherd', 1),
('Basenji', 1),
('Dalmatian', 1),
('Setter Irlandês', 1),
('Papillon', 1),
('Shih Tzu Imperial', 1),
('Tosa Inu', 1),
-- Raças de Felinos (fk_idespecie = 2)
('Persa', 2),
('Siamês', 2),
('Maine Coon', 2),
('Bengal', 2),
('Sphynx', 2),
('Ragdoll', 2),
('Scottish Fold', 2),
('Himalaio', 2),
('Norueguês da Floresta', 2),
('Exótico', 2),
-- Raças de Coelhos (fk_idespecie = 3)
('Netherland Dwarf', 3),
('Holland Lop', 3),
('Lionhead', 3),
('Mini Rex', 3),
('Flemish Giant', 3),
('Angorá', 3),
-- Raças de Equinos (fk_idespecie = 4)
('Quarto de Milha', 4),
('Puro Sangue Inglês', 4),
('Árabe', 4),
('Crioulo', 4),
('Frísio', 4),
('Andaluz', 4),
('Mangalarga Marchador', 4),
-- Raças de Suínos (fk_idespecie = 5)
('Large White', 5),
('Duroc', 5),
('Pietrain', 5),
('Landrace', 5),
('Hampshire', 5),
-- Raças de Bovinos (fk_idespecie = 6)
('Nelore', 6),
('Angus', 6),
('Holandês', 6),
('Gir', 6),
('Hereford', 6),
('Simental', 6),
('Jersey', 6),
-- Raças de Aves (fk_idespecie = 7)
('Calopsita', 7),
('Canário', 7),
('Periquito', 7),
('Papagaio', 7),
('Arara', 7),
('Cacatua', 7),
('Agapornis', 7);

INSERT INTO tipo_vac (tipo_vac) VALUES
('Antirrábica'),
('FeLV'),
('Giárdia'),
('Leptospirose'),
('Leishmaniose'),
('Tosse dos Canis'),
('V8'),
('V10');

INSERT INTO nome_vac (nome_vac, fk_idtipo_vac, laboratorio_nome_vac, valor_nome_vac) VALUES
('Nobivac', 1, 'MSD', 60),
('Felocell', 2, 'Zoetis', 150),
('GiardiaVax', 3, 'Zoetis', 80),
('Guard-Vac', 4, 'Zoetis', 70),
('Leishmune', 5, 'Zoetis', 120),
('BronchiGuard', 6, 'Zoetis', 70),
('Vanguard B Oral', 6, 'Zoetis', 130),
('Vanguard HTLP', 7, 'Zoetis', 80),
('Vanguard Plus', 8, 'Zoetis', 85);
